# A list of Warp Route token configs
# These configs will be merged with the warp routes in the configured registry
# The input here is typically the output of the Hyperlane CLI warp deploy command
---
tokens:
  - chainName: arbitrum
    standard: EvmHypCollateral
    decimals: 6
    symbol: USDC
    name: USD Coin
    addressOrDenom: "0x291DEf3aAC00E6F74a1f54e1B48381366f53199F"
    collateralAddressOrDenom: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"
    connections:
      - token: ethereum|base|0xA942b939D423A4081A191d0C7a3061a34b6481D4
      - token: ethereum|endurance|0xd564CE54001c3DBCD4AEAE5B1CA31153d870B51A
  - chainName: base
    standard: EvmHypCollateral
    decimals: 6
    symbol: USDC
    name: USD Coin
    addressOrDenom: "0xA942b939D423A4081A191d0C7a3061a34b6481D4"
    collateralAddressOrDenom: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
    connections:
      - token: ethereum|arbitrum|0x291DEf3aAC00E6F74a1f54e1B48381366f53199F
      - token: ethereum|endurance|0xd564CE54001c3DBCD4AEAE5B1CA31153d870B51A
  - chainName: endurance
    standard: EvmHypCollateralFiat
    decimals: 6
    symbol: USDC
    name: USD Coin
    addressOrDenom: "0xd564CE54001c3DBCD4AEAE5B1CA31153d870B51A"
    collateralAddressOrDenom: "0x2f8984788fbf4A3ecd4B3A0f33dd9FE7D08d6515"
    connections:
      - token: ethereum|arbitrum|0x291DEf3aAC00E6F74a1f54e1B48381366f53199F
      - token: ethereum|base|0xA942b939D423A4081A191d0C7a3061a34b6481D4